language: cpp
compiler: gcc
install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt593-trusty
    - sudo apt update
    - sudo apt install libqt4-dev qt4-qmake build-essential libgl1-mesa-dev
    - sudo apt install qt59-meta-minimal qtdeclarative5-dev

script:
    - source /opt/qt59/bin/qt59-env.sh
    - mkdir out
    - cd out
    - qmake ../acorn.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug && /usr/bin/make
