language: cpp
compiler: gcc
install:
    - sudo apt-get update
    - sudo apt-get install libqt4-dev qt4-qmake build-essential libgl1-mesa-dev
    - sudo add-apt-repository --yes ppa:beineri/opt-qt593-trusty
    - sudo apt-get install qt5-qmake

script:
    - qmake -project
    - qmake acorn.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug && /usr/bin/make qmake_all
    - make
